[package]
name = "schnorr_example_rust"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
candid = "=0.10.4"
ed25519-dalek = "2.1"
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4"
ic-cdk = "0.13"
k256 = { git = "https://github.com/altkdf/elliptic-curves", branch = "schnorr_canister", features = ["schnorr"] }
sha2 = "0.10"
serde = "1.0"
serde_bytes = "0.11"

[dev-dependencies]
flate2 = "1.0"
pocket-ic = "3.1"
