# Known failure: https://dfinity.atlassian.net/browse/EM-9
name: motoko-invoice-canister-e2e
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/invoice-canister/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-invoice-e2e.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-invoice-canister-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        env:
          NODE_VERSION: 19.8.1
        run: bash .github/workflows/provision-darwin.sh
      - name: Install vessel
        run: |
          pushd motoko/invoice-canister
          set -x
          curl --location --output vessel-macos "https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-macos"
          [ ! -d $HOME/bin ] && mkdir $HOME/bin
          mv ./vessel-macos $HOME/bin/vessel
          chown -R "$(whoami)" $HOME/bin && chmod -R +x $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          popd
      - name: Set configured networks.json 
        run: |
          cat > ~/.config/dfx/networks.json << EOF
          {
            "local": {
              "bind": "127.0.0.1:8080",
              "type": "ephemeral",
              "replica": {
                "subnet_type": "system"
              }
            }
          }
          EOF
      - name: Motoko Invoice Canister Darwin
        run: |
          dfx extension install nns --version 0.2.1
          pushd motoko/invoice-canister
          make e2e
          dfx stop
          popd
      - name: Remove networks.json
        run: rm ~/.config/dfx/networks.json
  motoko-invoice-canister-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Install vessel
        run: |
          pushd motoko/invoice-canister
          set -x
          curl --location --output vessel-linux64 "https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64"
          [ ! -d $HOME/bin ] && mkdir $HOME/bin
          mv ./vessel-linux64 $HOME/bin/vessel
          chown -R "$(whoami)" $HOME/bin && chmod -R +x $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          popd
      - name: Set configured networks.json 
        run: |
          cat > ~/.config/dfx/networks.json << EOF
          {
            "local": {
              "bind": "127.0.0.1:8080",
              "type": "ephemeral",
              "replica": {
                "subnet_type": "system"
              }
            }
          }
          EOF
      - name: Set configured canister_ids.json
        run: |
          cat > ~/.config/dfx/canister_ids.json << EOF
          {
            "local": {
              "invoice": "q4eej-kyaaa-aaaaa-aaaha-cai"
            }
          }
          EOF
      - name: Motoko Invoice Canister Linux
        run: |
          dfx extension install nns --version 0.2.1
          pushd motoko/invoice-canister
          make e2e
          dfx stop
          popd
      - name: Remove canister_ids.json
        run: rm ~/.config/dfx/canister_ids.json
      - name: Remove networks.json
        run: rm ~/.config/dfx/networks.json