# Known failure: https://dfinity.atlassian.net/browse/EM-5
name: motoko-ledger-transfer
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/ledger-transfer/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-ledger-transfer-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-ledger-transfer-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Ledger Transfer Darwin
        run: |
          pushd motoko/ledger-transfer
          bash ./demo.sh
          popd
  motoko-ledger-transfer-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@main
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Ledger Transfer Linux
        run: |
          pushd motoko/ledger-transfer
          bash ./demo.sh
          popd
