name: motoko-quicksort
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/quicksort/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-quicksort-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-quicksort-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-quicksort-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
