name: motoko-phone-book
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/phone-book/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-phone-book-example.yaml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-phone-book-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-phone-book-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
