name: motoko-simple-to-do
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-simple-to-do-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Simple To-Do Darwin
        run: |
          dfx start --background
          pushd motoko/simple-to-do
          make test
          popd
  motoko-simple-to-do-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Simple To-Do Linux
        run: |
          dfx start --background
          pushd motoko/simple-to-do
          make test
          popd
