name: motoko-simple-to-do
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/simple-to-do/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-simple-to-do-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-simple-to-do-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-simple-to-do-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
