name: motoko-encrypted-notes
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-encrypted-notes-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Encrypted Notes Darwin (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=motoko MATCHERS="$(dfx cache show)/motoko-matchers/src"
          popd
      - name: Motoko Encrypted Notes Darwin (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=motoko
          popd
  motoko-encrypted-notes-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Encrypted Notes Linux (unit tests)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-unit BUILD_ENV=motoko MATCHERS="$(dfx cache show)/motoko-matchers/src"
          popd
      - name: Motoko Encrypted Notes Linux (e2e)
        run: |
          pushd motoko/encrypted-notes-dapp
          make test-e2e BUILD_ENV=motoko
          popd