name: motoko-quicksort
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-quicksort-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Quicksort Darwin
        run: |
          dfx start --background
          pushd motoko/quicksort
          make test
          popd
  motoko-quicksort-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Quicksort Linux
        run: |
          dfx start --background
          pushd motoko/quicksort
          make test
          popd
