name: rust-simd
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/simd/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-simd-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-simd-example-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: DFX_VERSION="0.20.2-beta.0" bash .github/workflows/provision-darwin.sh
      - name: Remove networks.json
        run: rm -f ~/.config/dfx/networks.json
      - name: Rust SIMD Darwin
        run: |
          dfx start --background
          pushd rust/simd
          make test
          popd
  rust-simd-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: DFX_VERSION="0.20.2-beta.0" bash .github/workflows/provision-linux.sh
      - name: Remove networks.json
        run: rm -f ~/.config/dfx/networks.json
      - name: Rust SIMD Linux
        run: |
          dfx start --background
          pushd rust/simd
          make test
          popd
