name: rust-periodic_tasks
on:
  push:
    branches:
      - master
      - attempt-dfx-0.16.0
  pull_request:
    paths:
      - rust/periodic_tasks/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-periodic_tasks-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-periodic_tasks-example-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: DFX_VERSION="0.16.0" bash .github/workflows/provision-darwin.sh
      - name: Rust Periodic Tasks Darwin
        run: |
          dfx start --background
          pushd rust/periodic_tasks
          make test
          popd
  rust-periodic_tasks-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: DFX_VERSION="0.16.0" bash .github/workflows/provision-linux.sh
      - name: Rust Periodic Tasks Linux
        run: |
          dfx start --background
          pushd rust/periodic_tasks
          make test
          popd
