name: rust-send-http-post
on:
  pull_request:
    paths-ignore:
      - rust/send-http-post/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-send-http-post-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-send-http-post-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  rust-send-http-post-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'