name: rust-defi
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/defi/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-defi-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-defi-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Defi Darwin
        run: |
          pushd rust/defi
          bash ./scripts/install.sh
          bash ./test/demo.sh
          bash ./test/trade.sh
          bash ./test/transfer.sh
          popd
  rust-defi-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Defi Linux
        run: |
          pushd rust/defi
          bash ./scripts/install.sh
          bash ./test/demo.sh
          bash ./test/trade.sh
          bash ./test/transfer.sh
          popd
