# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: rust-threshold-schnorr
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/threshold-schnorr/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/provision-pocket-ic-server.sh
      - .github/workflows/rust-threshold-schnorr-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-threshold-schnorr-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Provision PocketIC
        run: bash .github/workflows/provision-pocket-ic-server.sh
      - name: Rust Threshold Schnorr Darwin
        run: |
          dfxvm default 0.22.0-beta.0
          dfx start --background
          pushd rust/threshold-schnorr
          make deploy
# This should be re-enabled when Pocket IC supports threshold Schnorr
# sleep 10
# make test
  rust-threshold-schnorr-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Provision PocketIC
        run: bash .github/workflows/provision-pocket-ic-server.sh
      - name: Rust Threshold Schnorr Linux
        run: |
          dfxvm default 0.22.0-beta.0
          dfx start --background
          pushd rust/threshold-schnorr
          make deploy
# This should be re-enabled when Pocket IC supports threshold Schnorr
# sleep 10
# make test
