name: rust-send-http-post-example
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/send_http_post/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-send-http-post-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-send-http-post-example-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Send HTTP POST Darwin
        run: |
          dfx start --background
          pushd rust/send_http_post
          RUSTFLAGS=-Ctarget-cpu=mvp make test
          popd
  rust-send-http-post-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Send HTTP POST Linux
        run: |
          dfxvm update
          dfx start --background
          pushd rust/send_http_post
          RUSTFLAGS=-Ctarget-cpu=mvp make test
          popd
