name: rust-nft-wallet
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/nft-wallet/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-nft-wallet-example.yml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-nft-wallet-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Install icx-asset
        run: cargo install --locked icx-asset
      - name: Rust NFT Wallet Darwin
        run: |
          pushd rust/nft-wallet
          dfx start --background --host 127.0.0.1:8000
          bash ./deploy.sh
          dfx canister call nftwallet owned_nfts
          popd
  rust-nft-wallet-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Install icx-asset
        run: cargo install --locked icx-asset
      - name: Rust NFT Wallet Linux
        run: |
          pushd rust/nft-wallet
          dfx start --background --host 127.0.0.1:8000
          bash ./deploy.sh
          dfx canister call nftwallet owned_nfts
          popd
