name: rust-tokens_transfer
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/tokens_transfer/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-tokens-transfer-example.yml
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-tokens_transfer-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Rust Tokens Transfer Darwin
        run: |
          pushd rust/tokens_transfer
          bash ./demo.sh
          popd
  rust-tokens_transfer-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Rust Tokens Transfer Linux
        run: |
          pushd rust/tokens_transfer
          bash ./demo.sh
          popd
